---
  # use the new container infrastructure
  sudo: required
  dist: trusty

  language: python
  python: "2.7"

  script:
    - echo $pubkey > ~/.ssh/authorized_keys
    - echo $privkey > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - ssh -R 9999:localhost:22 -o StrictHostKeyChecking=no travisci@$bouncehostip
