---
  # use the new container infrastructure
  sudo: required
  dist: trusty

  language: python
  python: "2.7"

  script:
    - echo travis:$sshpassword | sudo chpasswd
    - sudo apt-get install sshpass
    - sshpass -p $sshpassword ssh -R 9999:localhost:22 -o StrictHostKeyChecking=no travisci@$bouncehostip
